name: jaappalante
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hexcolor: ^3.0.1  # Gardez la dernière version ici
  hexcolorname: ^0.0.9 
  get: ^4.6.6 # Ajout de la dépendance Get
  flutter_svg: ^2.0.15
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.0.0
  change_app_package_name: ^1.4.0
  firebase_core: ^3.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
   - assets/images/ # Répertoire des images
